"""FreeCAD Mod InitGui template (class-based — survives FreeCAD re-exec)."""

from __future__ import annotations


def render_init_gui(*, live: str, step: str, flag: str, heartbeat: str) -> str:
    return f'''# Auto-generated by Kala — class-based reload + heartbeat.
import os
import time

try:
    from PySide6 import QtCore
except ImportError:
    try:
        from PySide2 import QtCore
    except ImportError:
        from PySide import QtCore

import FreeCAD as App
import FreeCADGui as Gui


class _KalaWatcher(QtCore.QObject):
    def __init__(self):
        super().__init__()
        self.LIVE = r"{live}"
        self.STEP = r"{step}"
        self.FLAG = r"{flag}"
        self.HEARTBEAT = r"{heartbeat}"
        self._state = {{"mtime": None, "flag": None, "step": None}}
        self._last_reload = 0.0
        self._pending = False

    def beat(self):
        import time as _time
        try:
            d = os.path.dirname(self.HEARTBEAT)
            if d:
                os.makedirs(d, exist_ok=True)
            with open(self.HEARTBEAT, "w", encoding="utf-8") as fh:
                fh.write(str(_time.time()))
        except Exception as exc:
            App.Console.PrintError("[Kala] heartbeat failed: " + str(exc) + "\\n")

    def open_path(self, path):
        try:
            mw = Gui.getMainWindow()
            for w in mw.findChildren(QtCore.QObject):
                try:
                    title = w.windowTitle() if hasattr(w, "windowTitle") else ""
                except Exception:
                    title = ""
                if title and ("Start page" in title or "Start Page" in title):
                    try:
                        (w.parent() or w).close()
                    except Exception:
                        pass
        except Exception:
            pass
        # Soft reopen: close only previous kala docs, keep FreeCAD window alive
        for name in list(App.listDocuments().keys()):
            doc = App.getDocument(name)
            try:
                fname = os.path.abspath(doc.FileName or "")
            except Exception:
                fname = ""
            if fname == os.path.abspath(path) or name.startswith("kala_live") or name.startswith("Unnamed"):
                # Only close our live docs / empty leftovers — never quit the app
                try:
                    App.closeDocument(name)
                except Exception:
                    pass
        lower = path.lower()
        if lower.endswith((".step", ".stp")):
            import ImportGui
            ImportGui.open(path)
        else:
            if hasattr(App, "openDocument"):
                App.openDocument(path)
            else:
                App.open(path)
        try:
            Gui.ActiveDocument = Gui.getDocument(App.ActiveDocument.Name)
            Gui.activeDocument().activeView().viewAxonometric()
            Gui.SendMsgToActiveView("ViewFit")
            mw = Gui.getMainWindow()
            mw.raise_()
            mw.activateWindow()
        except Exception as exc:
            App.Console.PrintWarning("[Kala] ViewFit: " + str(exc) + "\\n")

    def reload(self):
        import time as _time
        now = _time.time()
        # Debounce: mid-run tool syncs rewrite STEP every few hundred ms;
        # collapsing them stops the "window keeps closing/reopening" feel.
        if now - self._last_reload < 1.2:
            self._pending = True
            self.beat()
            return
        self._pending = False
        self._last_reload = now
        path = None
        if os.path.isfile(self.STEP) and os.path.getsize(self.STEP) > 100:
            path = self.STEP
        elif os.path.isfile(self.LIVE) and os.path.getsize(self.LIVE) > 64:
            path = self.LIVE
        if path is None:
            App.Console.PrintWarning("[Kala] no live STEP/FCStd yet\\n")
            self.beat()
            return
        App.Console.PrintMessage("[Kala] Reloading " + path + "\\n")
        try:
            self.open_path(path)
            App.Console.PrintMessage("[Kala] Design visible in GUI\\n")
        except Exception as exc:
            App.Console.PrintError("[Kala] open failed: " + str(exc) + "\\n")
        self.beat()

    def tick(self):
        import time as _time
        self.beat()
        try:
            mtime = os.path.getmtime(self.LIVE) if os.path.isfile(self.LIVE) else None
        except OSError:
            mtime = None
        try:
            flag_m = os.path.getmtime(self.FLAG) if os.path.isfile(self.FLAG) else None
        except OSError:
            flag_m = None
        try:
            sm = os.path.getmtime(self.STEP) if os.path.isfile(self.STEP) else None
        except OSError:
            sm = None
        changed = False
        if mtime is not None and mtime != self._state["mtime"]:
            self._state["mtime"] = mtime
            changed = True
        if flag_m is not None and flag_m != self._state["flag"]:
            self._state["flag"] = flag_m
            changed = True
        if sm is not None and self._state.get("step") != sm:
            self._state["step"] = sm
            changed = True
        if changed or (self._pending and (_time.time() - self._last_reload) >= 1.2):
            self.reload()


_old_timer = getattr(Gui, "_kala_reload_timer", None)
if _old_timer is not None:
    try:
        _old_timer.stop()
    except Exception:
        pass

_watcher = _KalaWatcher()
_timer = QtCore.QTimer()
_timer.setInterval(1000)
_timer.timeout.connect(_watcher.tick)
_timer.start()
Gui._kala_watcher = _watcher
Gui._kala_reload_timer = _timer
_watcher.beat()
App.Console.PrintMessage("[Kala] Watching " + _watcher.LIVE + " / " + _watcher.STEP + "\\n")
QtCore.QTimer.singleShot(800, _watcher.reload)
'''
